# Generated by Django 5.2.3 on 2025-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10)),
                ('machine_name', models.CharField(max_length=100)),
                ('unique_identifier', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
