# Generated by Django 5.2.3 on 2025-07-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_assigned_by_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='unique_identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
