# Generated by Django 5.2.3 on 2025-07-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_machine_is_assigned_alter_machine_machine_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='task',
            name='accessibility_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='activity_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='material',
            field=models.CharField(choices=[('Soil', 'Soil'), ('Sand', 'Sand'), ('Gravel', 'Gravel'), ('Debris', 'Debris'), ('Concrete', 'Concrete')], default='Soil', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], default='Day', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_complexity',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Moderate', 'Moderate'), ('Complex', 'Complex')], default='Simple', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Excavation', 'Excavation'), ('Grading', 'Grading'), ('Transport', 'Transport')], default='Excavation', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='terrain_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Sloped', 'Sloped'), ('Uneven', 'Uneven'), ('Rugged', 'Rugged')], default='Flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
